# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://maximmaximov.github.io/
baseurl: /
title: Maxim Maximov 
author: Maxim Maximov
description: Personal website and resume
avatar: profile.jpg
github: MaximovMaxim
email: maximmaximov@hotmail.com
#linkedin: juraj-tomori
vimeo: maximmaximov
#youtube: seals77
#wordpress: jurajtomori
#google_analytics: UA-136248017-1


# needed for travis-ci build
exclude: [vendor]
